### PR TITLE
adding support for window events

### PR DESCRIPTION
**Pull request by phaus**
I would like to persists the windows size and position over application starts.
The first step for this is to catch all these Events.
This is done within this change

### CODE REVIEW

**Comment by phaus** [comment]
Hi @mojbro. Do you have - by any chance  - some time to review this MR? :-).
That would be awesome.

**Comment by mojbro** [comment]
Hi @phaus. Sorry it’s been quiet from my side for a while. Life caught up with me. But I’ll make sure to go through your contributions this weekend! Very grateful for your engagement. Maybe this can turn out useful for others as well soon!

**Comment by phaus** [comment]
Any concerns about just merging this? ;-)

**Comment by mojbro** [comment]
Hey, so sorry for my silence! I say go for it. Feel free to take responsibility over this project and just do what you like :-) I like the pull request approach for visibility, but please don't wait for me. I hope to get back into it soon if I find a little more time to actually start hacking too.

**Pull request merged**
