### PR TITLE
Implement some TextField functions

### PR DESCRIPTION
**Pull request by StarHack**
This pull request extends the TextField class with new functionality:

- textField.SetFontFamily("Courier New")
- textField.SetFontSize(20)
- textField.SetBackgroundColor("#0000FF33")
- textField.SetColor("#FF0000FF")
- textField.SetBorderColor("#00FF00FF")
- textField.SetBorderWidth(3)
- textField.SetEnabled(true)
- textField.SetEditable(true)

@mojbro @phaus

### CODE REVIEW

**Comment by mojbro** [comment]
Cool!

I don't really work with this project anymore, as you might have guessed, but I'm happy for new contributions. Have you tested it and feel good about it? If yes, then I'll happily merge this PR.

**Comment by StarHack** [comment]
@mojbro Sorry to hear that as I planned to contribute more to this. Yes it works.

**Comment by mojbro** [comment]
@StarHack It's open source, so feel free! I can add you as a contributor if you're interested in continuing development. If it grows to be more usable, you'll perhaps find more users and contributors.

**Comment by phaus** [comment]
thx for the contribution @StarHack - I have not much free time at the moment. 
I did plan to use this project again. 
Great to have another contributor here.

**Comment by StarHack** [comment]
@mojbro Sure, why not.

**Pull request merged**
